# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://geographyas.info # or your custom domain name
title : Geography AS Notes

baseurl: /

author :
  name : Alex Jackson
  email : 
  github : alexjohnj
  twitter : alexjohnj
